### ISSUE TITLE
Ability to remove context menu items programmatically

### ISSUE THREAD

**Issue by truefusion** [iVis-at-Bilkent/cytoscape.js-edge-editing#52]
Would like a cleaner way to remove specific menu items from the context menu. Providing an empty string or a boolean false value to the menu item titles had no effect, so I'm currently doing it through style sheets. But doing it this way isn't going to prevent the menu from activating though there be a lack of children.

**Comment by msalihaltun** [comment]
Hello @truefusion. 

Could you elaborate on why you want to remove specific context menu items? The menu items of this extension reflect the functionality. There is no other way than using context menu items to add anchor points if an edge is doesn't already have bend or control points.

Also, there is already an option to this extension called `enableMultipleAnchorRemovalOption` which is done through context menu selectors [here](https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/blob/149c0aa59b0f5d2a39a3150b81f85f0f01105333/src/UIUtilities.js#L355). You could try removing items that way instead of stylesheets.

**Comment by truefusion** [comment]
While that provides a bit of insight, it doesn't help me.

While I can do something like this:
```js
var menus = cy.contextMenus('get');
menus.removeMenuItem('cy-edge-bend-editing-cxt-add-bend-point0');
menus.removeMenuItem('cy-edge-control-editing-cxt-add-control-point0');
```
The app errors out because it failed to find the menu items. The edge-editing library is clearly designed under the assumption that no one will desire to change anything after it is implemented into their app. Better would be if it were designed to take into consideration that people would want to fine-tune things to their liking. Providing an empty string or a boolean false value to the menu item titles to remove the undesired menu items would be a simple way of handling this.

**Comment by truefusion** [comment]
@canbax Turns out I cloned the wrong branch. But can you verify an anomaly I'm now having? The UI seems to deselect and re-select the edge upon right-clicking a control point. This didn't happen before.

**Comment by canbax** [comment]
@truefusion I observed the anomaly but this anomaly is irrelevant from the last 2 commits. I go back to the commit  4da4f4f7aac89a1c0649fd1cda5372b1213693f6 and I still observed this. This might be another independent issue.

**Comment by hasanbalci** [comment]
I'm closing this issue, because one can now remove any context-menu item by assigning `false` value to its corresponding title option.
